In [7]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt

In [18]:
lista=np.array([79, 20, 26,  3, 94,  1,  5,  8, 41, 81, 35, 50, 55, 94, 99, 91, 46,
       28, 94, 58, 97, 91, 99, 37, 17, 41, 22, 28, 34, 36, 53, 21, 85, 70,
       63, 96, 95, 47, 18, 37, 24, 87, 94, 45, 57, 36, 87, 77, 60, 14, 10,
       32, 73, 22, 60, 45, 73, 83, 90, 70, 17, 65, 17, 11, 69, 31, 45, 69,
       67, 94, 23, 68, 83, 76, 22, 70, 23, 15, 92,  7, 90, 77, 24, 14, 59,
       71, 96,  1, 81,  2, 83, 84, 19, 55, 61, 29, 77, 20, 67, 26, 28, 71,
       87, 33, 36, 81, 80, 88, 42, 31,  9,  5, 83, 68, 85, 63,  9, 34, 75,
       50, 51, 10, 71, 24, 74, 22, 86, 76, 12, 68, 31, 27, 65, 92, 62, 24,
       31, 15, 80, 19, 59, 50,  1, 87,  5,  9, 40, 38, 14,  9, 34, 63, 57,
       92,  3, 21, 73, 70, 15, 21, 38, 14,  0, 34, 20, 66, 97, 23,  8, 30,
       78, 47,  9, 88, 11, 11, 25, 55, 18,  8, 24, 29, 15, 29, 63, 41, 74,
       68, 11, 87, 32, 39,  1, 47, 32, 16, 52, 54, 73, 10])
lista

array([79, 20, 26,  3, 94,  1,  5,  8, 41, 81, 35, 50, 55, 94, 99, 91, 46,
       28, 94, 58, 97, 91, 99, 37, 17, 41, 22, 28, 34, 36, 53, 21, 85, 70,
       63, 96, 95, 47, 18, 37, 24, 87, 94, 45, 57, 36, 87, 77, 60, 14, 10,
       32, 73, 22, 60, 45, 73, 83, 90, 70, 17, 65, 17, 11, 69, 31, 45, 69,
       67, 94, 23, 68, 83, 76, 22, 70, 23, 15, 92,  7, 90, 77, 24, 14, 59,
       71, 96,  1, 81,  2, 83, 84, 19, 55, 61, 29, 77, 20, 67, 26, 28, 71,
       87, 33, 36, 81, 80, 88, 42, 31,  9,  5, 83, 68, 85, 63,  9, 34, 75,
       50, 51, 10, 71, 24, 74, 22, 86, 76, 12, 68, 31, 27, 65, 92, 62, 24,
       31, 15, 80, 19, 59, 50,  1, 87,  5,  9, 40, 38, 14,  9, 34, 63, 57,
       92,  3, 21, 73, 70, 15, 21, 38, 14,  0, 34, 20, 66, 97, 23,  8, 30,
       78, 47,  9, 88, 11, 11, 25, 55, 18,  8, 24, 29, 15, 29, 63, 41, 74,
       68, 11, 87, 32, 39,  1, 47, 32, 16, 52, 54, 73, 10])

In [19]:
display(lista)
#Numpy - cálculo da variância
variancia=np.var(lista)
print(variancia)


array([79, 20, 26,  3, 94,  1,  5,  8, 41, 81, 35, 50, 55, 94, 99, 91, 46,
       28, 94, 58, 97, 91, 99, 37, 17, 41, 22, 28, 34, 36, 53, 21, 85, 70,
       63, 96, 95, 47, 18, 37, 24, 87, 94, 45, 57, 36, 87, 77, 60, 14, 10,
       32, 73, 22, 60, 45, 73, 83, 90, 70, 17, 65, 17, 11, 69, 31, 45, 69,
       67, 94, 23, 68, 83, 76, 22, 70, 23, 15, 92,  7, 90, 77, 24, 14, 59,
       71, 96,  1, 81,  2, 83, 84, 19, 55, 61, 29, 77, 20, 67, 26, 28, 71,
       87, 33, 36, 81, 80, 88, 42, 31,  9,  5, 83, 68, 85, 63,  9, 34, 75,
       50, 51, 10, 71, 24, 74, 22, 86, 76, 12, 68, 31, 27, 65, 92, 62, 24,
       31, 15, 80, 19, 59, 50,  1, 87,  5,  9, 40, 38, 14,  9, 34, 63, 57,
       92,  3, 21, 73, 70, 15, 21, 38, 14,  0, 34, 20, 66, 97, 23,  8, 30,
       78, 47,  9, 88, 11, 11, 25, 55, 18,  8, 24, 29, 15, 29, 63, 41, 74,
       68, 11, 87, 32, 39,  1, 47, 32, 16, 52, 54, 73, 10])

863.0275


In [20]:
#Numpy - cálculo do desvio-padrão
desviopadrao=np.std(lista)
print(desviopadrao)

29.377329694851436


In [21]:
#Pandas - cálculo da variância
lista2=pd.Series(lista)
variancia=lista2.var()
print(variancia)


867.3643216080402


In [22]:
#Pandas - cálculo do desvio-padrão
desviopadrao=lista2.std()
print(desviopadrao)


29.451049584149633


In [23]:
display(lista2)


0      79
1      20
2      26
3       3
4      94
       ..
195    16
196    52
197    54
198    73
199    10
Length: 200, dtype: int64

In [28]:
media=np.mean(lista)
print(f'Média: {media}')


Média: 47.35


In [29]:
#coeficiente de variação (CV) é o desvio-padrão dividido pela média
coef_variacao=desviopadrao/media
print(coef_variacao)

0.6219862636568032


In [30]:
#cálculo da distância da variância em relação à média
distancia=variancia / (media**2)
print(distancia*100,'%')

38.686691217775035 %


Como eu interpreto isso?

1. distância <= 10%: minha dispersão é BAIXA;
2. distância > 10% e <= 25%: minha dispersão é MODERADA;
3. distância > 25%: minha dispersão é ALTA.
----

*Assimetria* é uma medida que nos indica a TENDÊNCIA DA DISTRIBUIÇÃO dos dados para o lado dos valores menores ou maiores.
 Para obtê-la, utilizamos o método do Pandas chamado skew().

 Como vou interpretar meus dados:

 1. Assimetria >= -0.5 e Assimetria <= 0.5: distribuição SIMÉTRICA (média aproximadamente igual à mediana);

 2. Assimetria > 0.5: distribuição ASSIMÉTRICA POSITIVA (média maior que a mediana; distribuição tendendo mais à direita);

 3. Assimetria < -0.5: distribuição ASSIMÉTRICA NEGATIVA (média menor que a mediana; distribuição tendendo mais à esquerda).

In [35]:
import pandas as pd
import numpy as np

In [37]:
salarios=np.array([1500, 2500, 3500, 3700, 4200, 5800, 9900, 13000, 15400, 25000])
salarios

array([ 1500,  2500,  3500,  3700,  4200,  5800,  9900, 13000, 15400,
       25000])

In [38]:
df_salarios={'Salários':[1500, 2500, 3500, 3700, 4200, 5800, 9900, 13000, 15400, 25000]}
df_salarios=pd.DataFrame(salarios)
display(df_salarios)

0
0   1500
1   2500
2   3500
3   3700
4   4200
5   5800
6   9900
7  13000
8  15400
9  25000